site_name: Henry Díaz Bordón
site_author: Henry Díaz Bordón
site_description: A potpourri of mathematics and computing
license: Licensed under CC BY-ND 4.0,
copyright: © 2026 All Rights Reserved.

theme:
  name: null
  custom_dir: 'theme'
  static_templates:
    - 404.html

nav:
  - Posts: posts.md
  - Problems: problems.md
  - Miscellanea: miscellanea.md

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.highlight:
      use_pygments: true
      noclasses: false
      linenums: true
      linenums_style: table

plugins:
  - geometry
  # - mathml